typography_spectrum: 0.5461869
color:
  saturation: 0.7341667313594371
  brandStrength: 0.6596905561164021
  rhythmicContrast: 0.009355993242934346
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  lightness: 0.2898388751782477
layout_spectrum: 1
author:
  name: Riftdweller
  email: riftdweller@gmail.com
name: riftDXB
navigation:
  - name: Instagram
    url: 'https://www.instagram.com/riftdweller/'
    type: external
  - name: 500 px
    url: 'https://500px.com/riftdweller'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: ''
