color:
  saturation: 0.1445364565588534
  brandStrength: 0.49897556751966476
  rhythmicContrast: 0.9946416134480387
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  lightness: 0.34965017111971974
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
navigation:
  - id: 'https://www.instagram.com/riftdweller/'
    url: 'https://www.instagram.com/riftdweller/'
    name: Instagram
    type: external
  - id: 'https://500px.com/riftdweller'
    url: 'https://500px.com/riftdweller'
    name: 500 px
    type: external
  - id: 'https://soundcloud.com/ahmed-al-numairy'
    url: 'https://soundcloud.com/ahmed-al-numairy'
    name: Soundcloud
    type: external
layout_spectrum: 0.12591122114099562
typography_spectrum: 0.20912387780845165
name: riftDXB
